---
title: "Применение средств и методов OSINT"
author: "Поспелова Ульяна БИСО-03-20"
engine: knitr
format:
    md:
        output-file: "README.md"
---

Open source intelligence (OSINT) – разведывательная дисциплина, включающая в себя поиск, выбор
и сбор разведывательной информации из общедоступных источников, а также её анализ.

Такими источниками информации могут быть:

- поисковые машины – Google, Bing, Yandex...

- специализированные поисковые системы – intelx.io, Shodan, Censys...

- порталы открытых данных – Github Awesome Lists, https://opendata.digital.gov.ru/

- материалы профильных конференций

- социальные сети, профильные блоги и т.д.

- официальные сайты компаний

## Цель работы

1. Освоить базовые подходы процессов OSINT.

2. Освоить современные инструменты поиска и сбора информации.

3. Освоить инструменты совместной работы в ходе аналитической деятельности.

## Задание

1. Собрать информацию о компании Innostage и их продуктах.

2. Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации.

3. Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.

4. Сформировать представление о рынке отечественных решений ИБ.

## Ход выполнения работы

### 1. Полное название компании (а также реквизиты)

Полное название компании - Общество с ограниченной ответственностью «Инностейдж»

Сокращенное наименование -	ООО «Инностейдж»

Юридический адрес - 420015, г. Казань, ул. Подлужная, д.60, оф.101

Фактический адрес -	420015, г. Казань, ул. Подлужная, д.60, оф.101

ИНН/КПП 1655428600/165501001, ОГРН 1191690099028

Телефон, факс -	+7 (843) 567-42-90

Электронная почта -	info@innostage-group.ru 

Сайт -	https://innostage-group.ru

Банковские реквизиты -	БИК 049205805 Р/с №40702810600020012857 в ПАО «АК БАРС» Банк, Кор/счет 30101810000000000805

[Источник](https://innostage-group.ru/company/requisites/)

### 2. Структура компании (при наличии публичной информации)

Не удалось найти публичную информацию о структуре компании Innostage.

### 3. Основные направления деятельности компании

#### Услуги

- Кибербезопасность

- Безопасность промышленных систем

- ИТ-инфраструктура

- Построение и модернизация ЦОД

- Инженерные системы зданий

- Бизнес-решения

- Внедрение средств защиты информации

- Инфокоммуникационные решения

- Решения промышленного Интернета вещей

[Источник](https://innostage-group.ru/services/)

#### Производимые продукты, основные сферы их применения, их достоинства

CyberART Сервисная служба киберзащиты:	ИБ - Управление информацией и событиями в системе безопасности (SIEM).

Innostage IRP:	ИБ - Управление информацией и событиями в системе безопасности (SIEM).

Innostage Платформа обучения кибербезопасности:	Системы дистанционного обучения	1.

InnoSTage Big Data Innostage:	Big Data, ИБ - Управление информацией и событиями в системе безопасности (SIEM).

Innostage Сервис по защите контейнеров Kubernetes:	ИБ - Управление информацией и событиями в системе безопасности (SIEM).

[Источник](https://www.tadviser.ru/index.php/%D0%9A%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F:InnoSTage_%28%D0%98%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B5%D0%B9%D0%B4%D0%B6%29)

#### Используемые технологии, языки программирования

Git 

SQL

Docker

Python

C#

PostgreSQL

Linux

JavaScript

Сетевые технологии

.NET

.NET Core

PHP

BPMN

CI/CD

Информационная безопасность

Redis

Jira

Рекрутмент

Администрирование Windows

Системное администрирование

ООП

HTML 

CSS

[Источник](https://career.habr.com/companies/innostage-group)

### 4. Основные клиенты компании (при наличии публичной информации)

ПАО «Газпром» — глобальная энергетическая компания.

ПАО «НК «РОСНЕФТЬ» – лидер российской нефтяной отрасли и крупнейшая публичная нефтегазовая корпорация мира.

ПАО «Татнефть» – одна из крупнейших российских нефтяных компаний. 

Группа компаний «ТАИФ» — крупный российский холдинг, контролирующий большую часть химической, нефтехимической и нефтегазоперерабатывающей отраслей Татарстана.

Группа «Интер РАО» — диверсифицированный энергетический холдинг, управляющий активами в России, а также в странах Европы и СНГ.

СИБУР является крупнейшей в России интегрированной нефтехимической компанией.

АО «Концерн Росэнергоатом» – российская энергетическая компания, оператор российских атомных электростанций.

ПАО «Нижнекамскнефтехим» - одна из крупнейших нефтехимических компаний Европы, занимает лидирующие позиции по производству синтетических каучуков и пластиков в Российской Федерации.

ПАО «Россети Ленэнерго» – одна из крупнейших и старейшая распределительная сетевая компания страны.

АО «Газпромбанк» — один из крупнейших коммерческих банков России.

ПАО "МРСК Центра" – ведущая электросетевая компания России.

АО «ЮниКредит Банк» является одним из крупнейших российских банков и входит в Группу UniCredit.

ПАО «Транснефть» — российская нефтепроводная компания, контролируемая государством.

ПАО «Банк Уралсиб» один из крупнейших универсальных банков федерального уровня.

ПАО «АК БАРС» БАНК - один из российских банков в Казани, имеющий сеть филиалов из 34 отделений.

Mriya Resort & SPA - курорт premium-класса в Крыму, включающий в себя пятизвездочный отель, медицинский и spa-центры международного уровня, современный конгресс-центр

Агентство по госзаказу РТ – оператор электронных площадок. Организует электронные торги для государства и коммерческих организаций.

АНО «Дирекция спортивных и социальных проектов» – официальный организатор крупных международных и всероссийских спортивных и иных мероприятий в г.Казани.

АО «Атомредметзолото» (Урановый холдинг «АРМЗ», Горнорудный дивизион Госкорпорации «Росатом») — преемник крупнейшего в мире комплекса по добыче урана, созданного в Советском Союзе.

АО «Техснабэкспорт» (TENEX) – один из ведущих мировых поставщиков продукции ядерного топливного цикла (ЯТЦ).

Госкорпорация Росатом – один из глобальных технологических лидеров, многопрофильный холдинг, объединяющий активы в энергетике, машиностроении, строительстве.

[Источник](https://innostage-group.ru/clients/)

### 5. Основные веб-сайты компании и ее продуктов

Основной веб-сайт - https://innostage-group.ru

CyberART Сервисная служба киберзащиты - https://cyberart.ru/

Innostage IRP - https://itsecurity.ru/

Соц. сети компании - https://vk.com/innostage , https://t.me/innostage_group , https://www.youtube.com/channel/UCCTKU2evNISQ231BwRnqquA , https://dzen.ru/innostage , https://habr.com/ru/companies/innostage/articles/ , https://vc.ru/u/1403047-innostage .

### 6. Публичные сотрудники компании, активные участники ИТ и ИБ-сообщества, участники профильных конференций, Twitter, Mastodon, Телеграмм-каналов и т.д.

Антон Кузьмин: https://realnoevremya.ru/articles/268624-prostye-pravila-nadezhnoy-kiberzaschity 

Ксения Рысаева: https://realnoevremya.ru/articles/256023-kseniya-rysaeva-samoe-glavnoe-byt-vnimatelnym-k-vhodyaschim-soobscheniyam

Владимир Дмитриев: https://www.anti-malware.ru/interviews/2021-12-23/37821 

Айдар Гузаиров: https://www.cnews.ru/reviews/security2021/interviews/ajdar_guzairov 

Наталья Алипова: группа ВКонтакте https://vk.com/innostage 

### 7. Уникальные достижения, ключевые продукты компании (при наличии)

По итогам 2021 года ГК Innostage стала лучшим партнером Check Point Software Technologies в России. 

[Источник](https://innostage-group.ru/press/news/gk-innostage-stala-luchshim-partnerom-check-point-software-v-rossii/)

ГК Innostage получила награду от ведущей компании в области кибербезопасности Positive Technologies в номинации «Лидер года 2021».

[Источник](https://dsmedia.pro/news/gk-innostage-priznana-luchshim-partnerom-positive-technologies)

Входим в топ - 10 крупнейших компаний в сфере защиты информации (по информации CNews и Tadviser).

Топ - 3 интеграторов в области кибербезопасности в России.

1000+ реализованных проектов, видим высокую оценку наших решений и востребованность на рынке.

430 млн событий за сутки, обрабатывает наш Центр предотвращения киберугроз CyberART.

Среди наших клиентов — компании из ТОП-200 крупнейших игроков рынка РФ.

Более 1000+ экспертов работает на площадках по всей России: в Казани, Москве, Саратове, Иннополисе и Санкт-Петербурге.

Финалист рейтинга «Лучших работодателей» по версии hh.ru.

[Источник](https://career.habr.com/companies/innostage-group)

## Выводы

Таким образом, с помощью процесса OSINT была получена информация о компании Innostage.